version: '3.8' # specify docker-compose version

services:
  db: # name of the service
    image: mysql:8.0 # specify image to build container from
    container_name: workshop_db # name of the container
    restart: always # restart the container if it fails
    environment: # environment variables
      MYSQL_ROOT_PASSWORD: Rlwl2023. # specify root password
      MYSQL_DATABASE: workshop # specify database name
      MYSQL_USER: root # specify user
      MYSQL_PASSWORD: Rlwl2023. # specify password
    ports:
      - "3307:3306" # specify port mapping
    volumes:
      - db_data:/var/lib/mysqli # specify volume to persist data

volumes:
  db_data: # name of the volume