insert into users (id, username, password, email, fullname, role) values (1, 'bfessler0', 'gD5&W*g1QBk{>', 'bfessler0@ucoz.com', 'Britt Fessler', 'Project Manager');
insert into users (id, username, password, email, fullname, role) values (2, 'sgooding1', 'oR7''zKR''`', 'sgooding1@soup.io', 'Skelly Gooding', 'Construction Expeditor');
insert into users (id, username, password, email, fullname, role) values (3, 'rmonnoyer2', 'oU2(yC?E', 'rmonnoyer2@gravatar.com', 'Ruby Monnoyer', 'Construction Worker');
insert into users (id, username, password, email, fullname, role) values (4, 'beasey3', 'cS8''H"b_`+', 'beasey3@purevolume.com', 'Bordy Easey', 'Subcontractor');
insert into users (id, username, password, email, fullname, role) values (5, 'sawde4', 'kU8#iv}2', 'sawde4@linkedin.com', 'Stanleigh Awde', 'Electrician');
insert into users (id, username, password, email, fullname, role) values (6, 'dramey5', 'wW8\>Q$pBC&', 'dramey5@nytimes.com', 'Darla Ramey', 'Estimator');
insert into users (id, username, password, email, fullname, role) values (7, 'pshemelt6', 'jE4''aaF)?*#mh', 'pshemelt6@drupal.org', 'Phillida Shemelt', 'Construction Foreman');
insert into users (id, username, password, email, fullname, role) values (8, 'mscurrell7', 'uN3$kB"5|A', 'mscurrell7@mozilla.com', 'Marcia Scurrell', 'Subcontractor');
insert into users (id, username, password, email, fullname, role) values (9, 'kguthrie8', 'dI4=xHC$zB0B6N', 'kguthrie8@timesonline.co.uk', 'Katti Guthrie', 'Electrician');
insert into users (id, username, password, email, fullname, role) values (10, 'mwynes9', 'gV3~)Sq`T0Q(CUl', 'mwynes9@techcrunch.com', 'Massimiliano Wynes', 'Construction Worker');
